name: Build Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.18.0'

      - name: Install Doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen graphviz

      - name: Create build directory
        run: cmake -E make_directory build

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build doc target
        run: cmake --build build --target doc

      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: doc
          path: doc/

  deploy-pages:
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    needs: build-doc
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Download HTML documentation artifact
        uses: actions/download-artifact@v4
        with:
          name: doc
          path: doc

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc/html
