name: Deploy GitHub Pages

on:
  workflow_run:
    workflows: ["Build Documentation"]
    types:
      - completed

jobs:
  deploy-pages:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download HTML documentation artifact
        uses: actions/download-artifact@v4
        with:
          name: doc-html
          path: doc-html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc-html
